GET http://localhost:5098/games

###
GET http://localhost:5098/games/3

###
POST http://localhost:5098/games
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild II",
    "genreId": 1,
    "price": 79.99,
    "releaseDate": "2019-12-10"
}

###
PUT http://localhost:5098/games/2
Content-Type: application/json

{
    "name": "The Legend of Zelda: Breath of the Wild",
    "genreId": 1,
    "price": 69.99,
    "releaseDate": "2017-03-03"
}

###
DELETE http://localhost:5098/games/3


###
GET http://localhost:5098/genres