// <auto-generated />
using MaterialCatalog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaterialCatalog.Api.Data.Migrations
{
    [DbContext(typeof(MaterialCatalogContext))]
    [Migration("20260927191512_CladdingCategories")]
    partial class CladdingCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MaterialCatalog.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ceramic Tile"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Porcelain Tile"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Natural Stone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brick"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Terracotta"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Timber Cladding"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Metal Cladding"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fibre Cement"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Composite Panel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Glass"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Render & Plaster"
                        });
                });

            modelBuilder.Entity("MaterialCatalog.Api.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("MaterialCatalog.Api.Models.Material", b =>
                {
                    b.HasOne("MaterialCatalog.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
